"""
Starter communication scenario dataset.

Two realistic scenarios per category — a reasonable starting set, not an
exhaustive library. `communication_service.ensure_seeded()` loads these
into MongoDB idempotently (upsert by slug).
"""

from __future__ import annotations

STARTER_SCENARIOS: list[dict] = [
    # --- Classmates ---
    {
        "slug": "start-conversation-new-classmate",
        "title": "Start a Conversation With a New Classmate",
        "category": "classmates",
        "mode": "social",
        "difficulty": "beginner",
        "description": "Practice starting a friendly, natural conversation with someone you just met in class.",
        "objective": "Introduce yourself and find common ground naturally.",
        "context": "You're sitting next to a new classmate you haven't spoken to before, waiting for class to start.",
        "ai_role": "A new classmate, friendly and a little curious",
        "user_role": "A student introducing themselves",
        "opening_message": "Hey, I don't think we've met — is this your first semester here?",
        "skills_targeted": ["conversation_starting", "small_talk", "social_confidence"],
        "tips": [
            "Ask an open-ended follow-up question instead of just yes/no answers.",
            "Share something about yourself too, not just questions.",
        ],
    },
    {
        "slug": "ask-classmate-about-assignment",
        "title": "Ask a Classmate About an Assignment",
        "category": "classmates",
        "mode": "daily_life",
        "difficulty": "beginner",
        "description": "Practice asking a classmate for clarification on a shared assignment.",
        "objective": "Get the information you need without sounding like you didn't pay attention.",
        "context": "You missed part of the assignment instructions and want to check with a classmate before the deadline.",
        "ai_role": "A classmate who understood the assignment",
        "user_role": "A student who needs clarification",
        "opening_message": "Hey! Did you get what we're supposed to submit for the assignment this week?",
        "skills_targeted": ["asking_for_help", "clarity", "conciseness"],
        "tips": [
            "Be specific about what part you're unsure of.",
            "Thank them for their time before ending the conversation.",
        ],
    },
    # --- Teachers ---
    {
        "slug": "ask-professor-clarification",
        "title": "Ask a Professor for Clarification",
        "category": "teachers",
        "mode": "professional",
        "difficulty": "beginner",
        "description": "Practice respectfully asking a professor to clarify something you didn't understand in class.",
        "objective": "Ask a clear, specific, and respectful question.",
        "context": "After a lecture on network security, you're still unclear on one concept and approach your professor.",
        "ai_role": "A professor, approachable but busy",
        "user_role": "A student seeking clarification",
        "opening_message": "Hi, did you have a question about today's lecture?",
        "skills_targeted": ["professional_communication", "asking_questions", "clarity"],
        "tips": [
            "Name the specific concept you're stuck on rather than saying 'I don't get it'.",
            "Keep the request concise and respectful of their time.",
        ],
    },
    {
        "slug": "request-project-feedback-professor",
        "title": "Request Project Feedback From a Professor",
        "category": "teachers",
        "mode": "professional",
        "difficulty": "intermediate",
        "description": "Practice asking a professor for detailed feedback on a project you submitted.",
        "objective": "Request specific, actionable feedback rather than a vague review.",
        "context": "You submitted a security research project last week and want more detailed feedback than the grade alone gave you.",
        "ai_role": "A professor who graded the project",
        "user_role": "A student requesting feedback",
        "opening_message": "Hi, I saw you wanted to talk about your project grade — what's on your mind?",
        "skills_targeted": ["professional_communication", "asking_questions", "conversation_flow"],
        "tips": [
            "Ask about specific sections rather than 'how did I do overall'.",
            "Show you've already thought about what could be improved.",
        ],
    },
    # --- Seniors ---
    {
        "slug": "ask-senior-about-internships",
        "title": "Ask a Senior About Internships",
        "category": "seniors",
        "mode": "professional",
        "difficulty": "beginner",
        "description": "Practice starting a conversation with a senior student about their internship experience.",
        "objective": "Learn how to ask useful, specific questions naturally.",
        "context": "You meet a senior student at a career fair who has completed a security internship.",
        "ai_role": "A senior student with internship experience",
        "user_role": "A junior student exploring internships",
        "opening_message": "Hey, I heard you did a security internship last summer — how was it?",
        "skills_targeted": ["conversation_starting", "professional_communication", "asking_questions"],
        "tips": [
            "Ask about their experience, not just 'how do I get one too'.",
            "Follow up on their answer instead of moving straight to your next question.",
        ],
    },
    {
        "slug": "ask-senior-cybersecurity-career",
        "title": "Ask a Senior About Cybersecurity Careers",
        "category": "seniors",
        "mode": "professional",
        "difficulty": "beginner",
        "description": "Practice starting a professional conversation with a senior about career paths in cybersecurity.",
        "objective": "Learn how to ask useful career questions naturally.",
        "context": "You meet a senior student who has completed a cybersecurity internship.",
        "ai_role": "Senior cybersecurity student",
        "user_role": "Junior cybersecurity student",
        "opening_message": "Hey, I heard you're doing an internship in cybersecurity. How has your experience been?",
        "skills_targeted": ["conversation_starting", "professional_communication", "asking_questions"],
        "tips": [
            "Ask what surprised them about the field.",
            "It's fine to admit you're still figuring out your path.",
        ],
    },
    # --- Recruiters ---
    {
        "slug": "introduce-yourself-recruiter",
        "title": "Introduce Yourself to a Recruiter",
        "category": "recruiters",
        "mode": "professional",
        "difficulty": "intermediate",
        "description": "Practice a concise, confident self-introduction at a career fair booth.",
        "objective": "Give a clear, memorable introduction in under 30 seconds worth of conversation.",
        "context": "You approach a recruiter's booth at a career fair and they ask you to tell them about yourself.",
        "ai_role": "A recruiter at a career fair, friendly but talking to many students",
        "user_role": "A student introducing themselves",
        "opening_message": "Hi there! Tell me a bit about yourself and what you're looking for.",
        "skills_targeted": ["professional_communication", "conciseness", "confidence"],
        "tips": [
            "Lead with what you're studying and one relevant strength or project.",
            "End with what you're looking for, so they know how to help you.",
        ],
    },
    {
        "slug": "ask-recruiter-internship-opportunities",
        "title": "Ask a Recruiter About Internship Opportunities",
        "category": "recruiters",
        "mode": "professional",
        "difficulty": "intermediate",
        "description": "Practice asking a recruiter specific questions about internship openings.",
        "objective": "Ask questions that show genuine interest and research.",
        "context": "You're speaking with a recruiter from a cybersecurity company and want to learn about their internship program.",
        "ai_role": "A company recruiter",
        "user_role": "A student interested in internships",
        "opening_message": "So, are you interested in our internship program?",
        "skills_targeted": ["asking_questions", "professional_communication", "conversation_flow"],
        "tips": [
            "Ask something specific about the role, not just 'do you have any openings'.",
            "Mention why you're interested in their company specifically.",
        ],
    },
    # --- Teammates ---
    {
        "slug": "discuss-project-responsibilities",
        "title": "Discuss Project Responsibilities With a Teammate",
        "category": "teammates",
        "mode": "professional",
        "difficulty": "intermediate",
        "description": "Practice dividing up responsibilities for a group project fairly and clearly.",
        "objective": "Propose a fair division of work and confirm mutual agreement.",
        "context": "Your team just got a new project and needs to divide the work before the next meeting.",
        "ai_role": "A teammate with their own opinions about the work split",
        "user_role": "A teammate proposing how to divide the work",
        "opening_message": "So how do you want to split this project up?",
        "skills_targeted": ["conversation_flow", "clarity", "professional_communication"],
        "tips": [
            "Propose something concrete rather than just asking open-endedly.",
            "Check that the other person actually agrees, don't just assume.",
        ],
    },
    {
        "slug": "resolve-teammate-disagreement",
        "title": "Resolve a Disagreement With a Teammate",
        "category": "teammates",
        "mode": "difficult_conversation",
        "difficulty": "advanced",
        "description": "Practice handling a disagreement about project direction professionally.",
        "objective": "Express disagreement respectfully while keeping the collaboration productive.",
        "context": "You and a teammate disagree about which technical approach to take for a shared project.",
        "ai_role": "A teammate who strongly prefers a different approach and is a bit defensive about it",
        "user_role": "A teammate proposing an alternative approach",
        "opening_message": "I really think we should just go with my approach — it's what I already started building.",
        "skills_targeted": ["disagreeing_respectfully", "difficult_conversations", "professional_tone"],
        "tips": [
            "Acknowledge their point before presenting your alternative.",
            "Focus on the project's goals, not on being 'right'.",
        ],
    },
    # --- Managers ---
    {
        "slug": "report-problem-to-manager",
        "title": "Report a Problem to Your Manager",
        "category": "managers",
        "mode": "professional",
        "difficulty": "intermediate",
        "description": "Practice reporting a project issue to a manager clearly and without panic.",
        "objective": "Communicate the problem, its impact, and a proposed next step.",
        "context": "You discovered a bug that will delay a deliverable and need to tell your manager before the next standup.",
        "ai_role": "A manager who values direct, solution-oriented updates",
        "user_role": "A team member reporting an issue",
        "opening_message": "Hey, you wanted to talk to me? What's up?",
        "skills_targeted": ["clarity", "professional_communication", "handling_difficult_conversations"],
        "tips": [
            "State the problem plainly before over-explaining the backstory.",
            "Offer at least one proposed next step, not just the bad news.",
        ],
    },
    {
        "slug": "give-progress-update-manager",
        "title": "Give a Progress Update to Your Manager",
        "category": "managers",
        "mode": "professional",
        "difficulty": "beginner",
        "description": "Practice giving a concise, useful status update in a 1:1.",
        "objective": "Summarize progress clearly without rambling or over-explaining.",
        "context": "Your manager asks for a quick update on your current task during a 1:1 meeting.",
        "ai_role": "A manager checking in during a routine 1:1",
        "user_role": "A team member giving a status update",
        "opening_message": "How's the task going? Any blockers?",
        "skills_targeted": ["conciseness", "clarity", "professional_communication"],
        "tips": [
            "Lead with status (on track / blocked / done), then details.",
            "Flag blockers explicitly instead of hoping they'll ask.",
        ],
    },
    # --- Everyday ---
    {
        "slug": "introduce-yourself-someone-new",
        "title": "Introduce Yourself to Someone New",
        "category": "everyday",
        "mode": "social",
        "difficulty": "beginner",
        "description": "Practice a natural, friendly self-introduction in a casual setting.",
        "objective": "Introduce yourself comfortably and keep a light conversation going.",
        "context": "You're at a community event and strike up a conversation with someone you haven't met before.",
        "ai_role": "A friendly stranger at a casual event",
        "user_role": "Someone introducing themselves",
        "opening_message": "Hi! I don't think we've met — I'm here for the first time, how about you?",
        "skills_targeted": ["conversation_starting", "social_confidence", "small_talk"],
        "tips": [
            "It's fine to keep it light — you don't need a deep topic right away.",
            "Ask a question back so it doesn't feel like an interview.",
        ],
    },
    {
        "slug": "practice-small-talk",
        "title": "Practice Small Talk",
        "category": "everyday",
        "mode": "social",
        "difficulty": "beginner",
        "description": "Practice keeping a light, casual conversation going naturally.",
        "objective": "Maintain a comfortable back-and-forth without the conversation stalling.",
        "context": "You're waiting in line with someone and a casual conversation starts.",
        "ai_role": "A friendly person also waiting in line",
        "user_role": "Someone making small talk",
        "opening_message": "This line is taking forever, huh?",
        "skills_targeted": ["conversation_flow", "social_confidence", "active_listening"],
        "tips": [
            "React to what they said before changing the subject.",
            "Light humor is fine — this doesn't need to be serious.",
        ],
    },
    # --- Professional ---
    {
        "slug": "networking-conversation",
        "title": "Have a Networking Conversation",
        "category": "professional",
        "mode": "professional",
        "difficulty": "intermediate",
        "description": "Practice a professional networking conversation at an industry event.",
        "objective": "Build a genuine professional connection, not just exchange business cards.",
        "context": "You're at a cybersecurity meetup and start talking to another attendee who works in the field.",
        "ai_role": "An industry professional at a networking event",
        "user_role": "A student networking professionally",
        "opening_message": "So, what brings you to this meetup?",
        "skills_targeted": ["professional_communication", "conversation_flow", "asking_questions"],
        "tips": [
            "Ask about their work before pivoting to what you want from them.",
            "A specific, genuine question beats generic small talk.",
        ],
    },
    {
        "slug": "ask-colleague-for-help",
        "title": "Ask a Colleague for Help",
        "category": "professional",
        "mode": "professional",
        "difficulty": "beginner",
        "description": "Practice asking a colleague for help without sounding unprepared.",
        "objective": "Ask for help clearly while showing you've already tried to solve it yourself.",
        "context": "You're stuck on a technical problem at work and need to ask a colleague for help.",
        "ai_role": "A colleague who is generally happy to help but busy",
        "user_role": "Someone asking for help",
        "opening_message": "Hey, what's up?",
        "skills_targeted": ["asking_for_help", "clarity", "professional_tone"],
        "tips": [
            "Briefly mention what you've already tried.",
            "Be specific about what kind of help you need.",
        ],
    },
    # --- Difficult conversations ---
    {
        "slug": "explain-missed-deadline",
        "title": "Explain a Missed Deadline",
        "category": "managers",
        "mode": "difficult_conversation",
        "difficulty": "advanced",
        "description": "Practice explaining a missed deadline honestly and professionally.",
        "objective": "Take ownership, explain briefly, and propose a path forward.",
        "context": "You missed a deadline on a deliverable and need to explain the situation to your manager.",
        "ai_role": "A manager who is disappointed but wants a constructive conversation",
        "user_role": "A team member who missed a deadline",
        "opening_message": "I noticed the deliverable wasn't submitted on time. What happened?",
        "skills_targeted": ["handling_difficult_conversations", "professional_tone", "clarity"],
        "tips": [
            "Own the delay without over-apologizing or making excuses.",
            "End with a concrete plan or revised timeline.",
        ],
    },
    {
        "slug": "disagree-respectfully",
        "title": "Disagree Respectfully",
        "category": "professional",
        "mode": "difficult_conversation",
        "difficulty": "advanced",
        "description": "Practice disagreeing with someone's approach professionally, without being dismissive or passive.",
        "objective": "State a differing opinion clearly and respectfully, and handle pushback.",
        "context": "A colleague proposes an approach in a meeting that you believe has a significant flaw.",
        "ai_role": "A colleague confident in their proposed approach, mildly defensive if challenged",
        "user_role": "A colleague who sees a problem with the proposal",
        "opening_message": "I think this approach will work well — any thoughts before we move forward?",
        "skills_targeted": ["disagreeing_respectfully", "difficult_conversations", "confidence"],
        "tips": [
            "Lead with a specific concern, not a vague objection.",
            "Stay calm and factual even if they push back.",
        ],
    },
]
