"""
Progress & Personal AI Profile document shapes (Step 11).

MongoDB is accessed directly via PyMongo (no ODM), so this module documents
the shape of documents in `learning_progress`, `user_weaknesses`,
`recommendations` and `personal_profiles` rather than mapping to them
automatically. See `app.services.progress` for the code that reads/writes
these documents.

These collections are *derived/cached* data: everything in them is computed
from the existing session collections (practice_sessions, ctf_sessions,
communication_sessions, interview_sessions, pressure_sessions) by
`ProgressService.recalculate()`. Nothing here is a primary source of truth,
and nothing here is a psychological or medical conclusion -- only observable
learning/performance signals (scores, attempts, completion), consistent with
the rest of the project's Step 10 "training, not diagnosis" stance.
"""

from __future__ import annotations

from datetime import datetime
from typing import Literal, NotRequired, TypedDict

from bson import ObjectId

Level = Literal["beginner", "developing", "intermediate", "proficient", "advanced"]
Confidence = Literal["low", "medium", "high"]
Severity = Literal["low", "medium", "high"]
Priority = Literal["low", "medium", "high"]
RecommendationType = Literal["practice", "ctf", "communication", "interview", "pressure"]
Trend = Literal["improving", "stable", "declining", "insufficient_data"]
SkillSource = Literal["cybersecurity_practice", "ctf", "interview"]


class LearningProgressDocument(TypedDict):
    """
    Shape of a document in the `learning_progress` collection.

    One document per (user_id, skill) pair -- `skill` is the category name as
    it appears in `cybersecurity_topics`/`practice_sessions` (e.g.
    "Networking", "Web Security"). Upserted by
    `app.services.progress.aggregation_service` from completed
    `practice_sessions` (primary signal), with CTF/interview activity in the
    same category folded in as supporting evidence only.
    """

    _id: ObjectId
    user_id: ObjectId
    skill: str
    category: str
    level: Level
    score: int
    confidence: Confidence
    attempts: int
    successful_attempts: int
    last_practiced_at: datetime | None
    updated_at: datetime


class WeaknessEvidenceDocument(TypedDict, total=False):
    average_score: int
    attempts: int
    threshold: int
    minimum_attempts: int


class UserWeaknessDocument(TypedDict):
    """Shape of a document in the `user_weaknesses` collection."""

    _id: ObjectId
    user_id: ObjectId
    area: str
    skill: str
    source: SkillSource | Literal["communication", "pressure"]
    severity: Severity
    evidence: WeaknessEvidenceDocument
    detected_at: datetime
    last_updated_at: datetime


class RecommendationDocument(TypedDict):
    """Shape of a document in the `recommendations` collection."""

    _id: ObjectId
    user_id: ObjectId
    type: RecommendationType
    area: str
    topic: str
    priority: Priority
    reason: str
    created_at: datetime
    completed: bool
    completed_at: NotRequired[datetime | None]


class TechnicalProfile(TypedDict):
    strong_areas: list[str]
    developing_areas: list[str]
    weak_areas: list[str]


class CommunicationProfile(TypedDict):
    strengths: list[str]
    improvement_areas: list[str]


class InterviewProfile(TypedDict):
    strengths: list[str]
    improvement_areas: list[str]


class PressureProfile(TypedDict):
    observed_indicators: list[str]
    improvement_areas: list[str]


class LearningPreferences(TypedDict):
    preferred_difficulty: str


class PersonalProfileDocument(TypedDict):
    """
    Shape of a document in the `personal_profiles` collection.

    One document per user. `ai_summary` (when present) is a natural-language
    interpretation of the deterministic fields below it, generated by the
    existing AIService/Gemini client -- it never introduces its own numbers,
    and the deterministic fields remain the source of truth. See
    `app.services.progress.profile_service`.
    """

    _id: ObjectId
    user_id: ObjectId
    technical_profile: TechnicalProfile
    communication_profile: CommunicationProfile
    interview_profile: InterviewProfile
    pressure_profile: PressureProfile
    learning_preferences: LearningPreferences
    recent_focus: list[str]
    recommended_focus: list[str]
    ai_summary: NotRequired[dict | None]
    updated_at: datetime
