"""
Daily practice planner (Step 19) -- pure functions, no database, no AI.

The plan is built *deterministically* from the output of the existing
personalization engine (profile, weaknesses, recommendations, difficulty), so:

* the same inputs always give the same plan (stable across refreshes),
* nothing is invented -- each task carries the real reasons it was chosen,
* no Gemini call is spent on planning. The questions themselves are still
  generated by the existing Step 17 practice engine when the user starts the task.

A plan is a short list of tasks, one per kind (cybersecurity / communication /
interview), each started through the existing module that already owns that
practice type. A task's ``config`` is exactly what that module's start API takes.
"""

from __future__ import annotations

from datetime import date

CYBERSECURITY, COMMUNICATION, INTERVIEW = "cybersecurity", "communication", "interview"

MINUTES_PER_QUESTION = 3
COMMUNICATION_MINUTES = 5
INTERVIEW_MINUTES = 10      # the shortest interview the engine offers is 5 questions
INTERVIEW_QUESTIONS = 5
MAX_CYBER_QUESTIONS = 10
LEVELS = ("beginner", "intermediate", "advanced")

_INTERVIEW_TYPE_BY_FOCUS = {
    "hr": "hr", "behavioral": "hr",
    "soc": "cybersecurity", "blue_team": "cybersecurity", "red_team": "cybersecurity",
    "penetration_testing": "cybersecurity",
    "networking": "technical", "linux": "technical", "web_security": "technical",
    "cybersecurity_technical": "technical",
}


def settings_fingerprint(*, goal_minutes: int, difficulty_pref: str) -> str:
    """Inputs that, when the user changes them, justify rebuilding an untouched plan."""
    return f"{goal_minutes}|{difficulty_pref}"


def _label(value: str) -> str:
    return value.replace("_", " ")


def _first(recs: list[dict], kind: str) -> dict | None:
    return next((r for r in recs if r["type"] == kind), None)


def _needs(pers: dict, recs: list[dict]) -> dict[str, int]:
    """How much the user needs communication vs interview practice (higher = more)."""
    goals = set(pers.get("learning_goals") or [])
    comm_rec, interview_rec = _first(recs, COMMUNICATION), _first(recs, INTERVIEW)
    weight = {"high": 3, "medium": 2, "low": 1}
    comm = weight.get((comm_rec or {}).get("priority"), 0) if comm_rec and comm_rec["basis"] == "performance" else 0
    interview = weight.get((interview_rec or {}).get("priority"), 0) if interview_rec else 0
    if "improve_communication" in goals:
        comm += 1
    if "prepare_for_interviews" in goals or pers.get("interview_focus"):
        interview += 1
    return {COMMUNICATION: comm, INTERVIEW: interview}


def choose_cyber_difficulty(pers: dict, pref: str, top_practice: dict | None) -> tuple[str, str]:
    """Adaptive when there is enough performance data; otherwise a concrete level."""
    if pref in LEVELS:
        return pref, f"You set your difficulty to {pref}."
    if pers.get("data_status") == "sufficient":
        return "adaptive", "Adaptive: difficulty follows your recent results."
    level = (top_practice or {}).get("difficulty") or pers.get("recommended_difficulty") or "beginner"
    return level, "Not enough practice data for adaptive mode yet, so this uses your experience level."


def concrete_level(pers: dict, pref: str) -> str:
    if pref in LEVELS:
        return pref
    level = pers.get("recommended_difficulty")
    return level if level in LEVELS else "beginner"


def pick_scenario(
    scenarios: list[dict], *, level: str, skill: str | None, recent_ids: set[str], today: date
) -> dict | None:
    """Deterministic scenario choice: matching skill, then level, avoiding recent ones; rotates by date."""
    if not scenarios:
        return None
    wanted = (skill or "").strip().lower().replace(" ", "_")

    def rank(s: dict) -> tuple:
        return (
            s["scenario_id"] in recent_ids,
            0 if wanted and wanted in (s.get("skills_targeted") or []) else 1,
            0 if s["difficulty"] == level else 1,
            s["slug"],
        )

    ranked = sorted(scenarios, key=rank)
    best = rank(ranked[0])[:3]
    tied = [s for s in ranked if rank(s)[:3] == best]
    return tied[today.toordinal() % len(tied)]


def build_plan(
    *, pers: dict, goal_minutes: int, difficulty_pref: str, scenarios: list[dict],
    recent_scenario_ids: set[str], today: date,
) -> dict:
    """Return ``{"tasks": [...], "focus": {...}, "rationale": [...]}`` for one day."""
    recs = pers.get("recommendations") or []
    top_practice = _first(recs, "practice")
    needs = _needs(pers, recs)
    ranked_extras = sorted((COMMUNICATION, INTERVIEW), key=lambda k: (-needs[k], k != (COMMUNICATION if today.toordinal() % 2 else INTERVIEW)))

    # Which extra tasks fit the time budget.
    if goal_minutes >= 25:
        extras = [COMMUNICATION, INTERVIEW]
    elif goal_minutes >= 15:
        extras = [ranked_extras[0]]
    elif goal_minutes >= 10:
        extras = [COMMUNICATION]
    else:
        extras = []
    extras_minutes = sum(COMMUNICATION_MINUTES if k == COMMUNICATION else INTERVIEW_MINUTES for k in extras)
    cyber_minutes = max(5, goal_minutes - extras_minutes)
    questions = max(1, min(MAX_CYBER_QUESTIONS, round(cyber_minutes / MINUTES_PER_QUESTION)))

    tasks: list[dict] = []
    difficulty, diff_reason = choose_cyber_difficulty(pers, difficulty_pref, top_practice)
    if top_practice:
        category = top_practice["topic"]
        weak = top_practice["basis"] == "performance"
        tasks.append({
            "task_id": CYBERSECURITY, "kind": CYBERSECURITY,
            "title": f"{'Strengthen' if weak else 'Practice'} {category}",
            "description": f"{questions} {category} question{'s' if questions != 1 else ''}, mixed formats.",
            "why": [*top_practice["reasons"][:2], diff_reason],
            "est_minutes": questions * MINUTES_PER_QUESTION,
            "route": "/cybersecurity/practice",
            "config": {"mode": "topic", "category": category, "difficulty": difficulty,
                       "question_type": "mixed", "question_count": questions},
            "focus_basis": top_practice["basis"],
        })
    else:
        tasks.append({
            "task_id": CYBERSECURITY, "kind": CYBERSECURITY,
            "title": "Personalized cybersecurity practice",
            "description": f"{questions} question{'s' if questions != 1 else ''} chosen from your profile.",
            "why": ["No weak area has been identified yet, so this follows your profile and goals.", diff_reason],
            "est_minutes": questions * MINUTES_PER_QUESTION,
            "route": "/cybersecurity/practice",
            "config": {"mode": "personalized", "category": None, "difficulty": difficulty,
                       "question_type": "mixed", "question_count": questions},
            "focus_basis": "profile",
        })

    level = concrete_level(pers, difficulty_pref)
    for kind in extras:
        if kind == COMMUNICATION:
            rec = _first(recs, COMMUNICATION)
            skill = rec["title"].removeprefix("Improve ").removesuffix(" in your answers") if rec else None
            scenario = pick_scenario(scenarios, level=level, skill=skill, recent_ids=recent_scenario_ids, today=today)
            if scenario is None:
                continue
            why = (rec["reasons"][:2] if rec else ["Short conversations build everyday and professional communication."])
            tasks.append({
                "task_id": COMMUNICATION, "kind": COMMUNICATION,
                "title": f"Communication: {scenario['title']}",
                "description": scenario["objective"],
                "why": why,
                "est_minutes": COMMUNICATION_MINUTES, "route": "/communication",
                "config": {"scenario_id": scenario["scenario_id"], "difficulty": level},
                "focus_basis": rec["basis"] if rec else "profile",
            })
        else:
            rec = _first(recs, INTERVIEW)
            focus = (pers.get("interview_focus") or [None])[0]
            itype = _INTERVIEW_TYPE_BY_FOCUS.get(focus or "", "technical")
            tasks.append({
                "task_id": INTERVIEW, "kind": INTERVIEW,
                "title": f"Interview practice ({_label(itype)})",
                "description": f"A short {INTERVIEW_QUESTIONS}-question {_label(itype)} interview.",
                "why": (rec["reasons"][:2] if rec else ["Regular mock interviews build confidence for real ones."]),
                "est_minutes": INTERVIEW_MINUTES, "route": "/interview",
                "config": {"interview_type": itype, "difficulty": level, "question_count": INTERVIEW_QUESTIONS,
                           "mode": "text"},
                "focus_basis": rec["basis"] if rec else "profile",
            })

    primary = tasks[0]
    return {
        "tasks": tasks,
        "focus": {"title": primary["title"], "topic": (primary["config"].get("category") or "Personalized"),
                  "basis": primary["focus_basis"]},
        "rationale": primary["why"],
        "difficulty": difficulty,
    }
